device_info:
  device:
    name: webcam
  manufacturer:
    name: Unspecified
    uuid: 50666eea-4170-48b7-9fd2-b29caf619620
  model:
    name: Unspecified
    uuid: f12633b4-fd08-48b6-80a0-713df096695b
  serial_number: 123456789
  device_classes:
  - class_identifier:
      name: usb_camera
      uuid: b25bf959-7ba9-46be-989e-5529026a00da
    subclasses:
    - webcam
  implemented_types:
  - com.robotraconteur.imaging.Camera
calibration:
  image_size:
    width: 1280
    height: 720
